# Configurations
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: pygments

# Needed for backward compatibility
gems: [jekyll-paginate]

# Permalinks
permalink:        /blog/:year/:month/:day/:title

# Setup
title:            'Mohsen Jalalian'
tagline:          'Mohsen Jalalian Page'
description:      'Mohsen Jalalian Developer for linux web and other'
url:              ''
baseurl:          ''

# Navigation
navigation:
- text: About
  url: /about/
- text: Resume
  url: /resume/
- text: Blog
  url: /blog/
- text: Tags
  url: /tags/
- text: Archive
  url : /archive/
- text: Search
  url: /search/


# Author Details
author:         'Mohsen Jalalian'

#Social Media links (Use complete URL except for email)
dribbble:
email:
facebook:       'https://www.facebook.com/mohsenjalalian'
flickr:
github:         'https://github.com/mohsenjalalian'
gplus:          'https://plus.google.com/jalalianmohsen/'
instagram:
pinterest:
linkedin:       'https://www.linkedin.com/in/mohsen-jalalian'
rss:
stackoverflow:  'https://stackoverflow.com/users/4834638/mohsen-jalalian'
twitter:        'https://twitter.com/mohsenjalalian4'

# Google Analytics
gahandler: ''

#if footersvg is 'true' the social media links will be shown top on the copy right in the footer
footersvg: 'true'

# Disqus
disqushandler: 'testingblogo'

# txtpen
txtpenhandler: 'testingblogo'

# Blog Configurations
paginate: 10 # Posts per page on the blog index
paginate_path: '/blog/page:num'
destination: ./_site

# Custom vars
version:          0.9x beta 2
